# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: "0xCYB3RW0LF"
# Description of the Site
description: Welcome to Omar Ahmed's Personal Website
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/omar-danasoury.jpg
# Keywords of the Site
site-keywords: Personal Website, Programming, Cyber Security, Kali Linux, CTFs
# URL for the Image of custom Favicon
favicon-url: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/favicon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: /assets/images/windows.jpg
# heroimage: https://source.unsplash.com/4Mw7nkQDByk # sudo image
# heroimage: https://source.unsplash.com/zGuBURGGmdY # glasses and code screens
# heroimage: https://source.unsplash.com/zvHhKiVuR9M # scripting screen
# heroimage: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/windows2.png # windows screen, the big file
# heroimage: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/windows.jpg # windows screen
heroimage: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/red-cli.gif # red-cli screen

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: omardanasoury8@gmail.com
# facebook_username: thedevslot
# twitter_username: thedevslot
# instagram_username: thedevslot
linkedin_username: 0xcyb3rw0lf
github_username:  0xcyb3rw0lf
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
tryhackme_username: 0xcyb3rw0lf
hackthebox_username: 631749


# Google Analytics
google-analytics: G-KEL847MTZM

# Disqus
# disqus-shortname: thedevslot
disqus-shortname:

# Name of the Author
author-name: "Omar Ahmed"
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/omar-danasoury.jpg
# 60 Words About the Author
author-about: I'm Omar Ahmed (0xCyb3rW0lf). As a senior computer science student @ University of Bahrain, I am passionate about cybersecurity, particularly offensive security, and have a strong interest in related research. I have a solid foundation in computer science and software development, making me a skilled and enthusiastic developer. Additionally, I enjoy exploring electronics and various aspects of technology and engineering.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linkedin.com/in/0xcyb3rw0lf

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: "https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/windows.jpg"
      description: ""
      tags:
        # - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
