# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Omar Eldanasoury
# Description of the Site
description: Welcome to My Personal Website
# URL of Image of the Site
site-image: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/omar-danasoury.jpg
# Keywords of the Site
site-keywords: Personal Website, Programming, Flutter, Cyber Security, Kali Linux, CTFs
# URL for the Image of custom Favicon
favicon-url: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/favicon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: /assets/images/windows.jpg
# heroimage: https://source.unsplash.com/4Mw7nkQDByk # sudo image
# heroimage: https://source.unsplash.com/zGuBURGGmdY # glasses and code screens
# heroimage: https://source.unsplash.com/zvHhKiVuR9M # scripting screen
# heroimage: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/windows2.png # windows screen, the big file
heroimage: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/windows.jpg # windows screen

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: omardanasoury8@gmail.com
# facebook_username: thedevslot
# twitter_username: thedevslot
# instagram_username: thedevslot
linkedin_username: omar-eldanasoury
github_username:  omar-danasoury
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
# disqus-shortname: thedevslot
disqus-shortname:

# Name of the Author
author-name: Omar Eldanasoury
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/omar-danasoury/personal-website/master/assets/images/omar-danasoury.jpg
# 60 Words About the Author
author-about: I am Omar Eldanasoury, a senior computer science student at the University of Bahrian + Member of Google Developers Student Clubs (GDSC). I am into software development and cybersecurity, and I like to do projects and share my knowledge with community. 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linkedin.com/in/omar-eldanasoury

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
